#!/usr/bin/env python
#
# fMBT, free Model Based Testing tool
# Copyright (c) 2012, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU Lesser General Public License,
# version 2.1, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.

"""fMBT stats tool - print statistics from test log

Usage: fmbt-stats [options] [logfile]

logfile is the XML log written by fmbt (fmbt -l logfile test.conf),
adapter logs are not supported.

Options:
  -f, --format=<fmt>
          fmt defines statistics to present. Available formats:

          times[:field]        - execution times of test steps
              data is sorted by the field ("min", "max", "median",
              "total", "count" or "name").

          speed[:n|"include="regex] - test step execution speed
              average execution speed of previous n (n2, ...) steps.
              If "include="regex is given, then only actions matching
              regex are included in the results.

          duration[:n|"include="regex] - test step durations
              the same as "speed", but show duration (s)
              instead of execution speed (steps/s).

          dist[:steps[,"uniq"][,"sort"]] - number of executed steps
              If the steps is "next" or "prev", shows the distribution
              of next or previous steps. "simple" shows only total
              number of executed steps.
              If "uniq" is given, only unique next or previous steps
              are counted. By default all executions are counted.
              If "sort" is given, data is sorted by counted steps.
              The default is sort by names.

          tagdist[:"from"|"to"[,"tags="<regexp>] - number of steps on tags
              The default is "from", that is, present numbers of test
              steps starting *from* states with different tags.
              "tags:regexp" includes only tags matching the regular
              expression.

          cov[:xaxis[,"all"]]  - test coverage
              Present coverage as a function of "time" or "steps"
              (xaxis). Coverage on every step is printed if "all" is
              given, otherwise only on steps where coverage changes
              (the default).

  -h, --help
          print this help.

  -o, --output=<file>
          output will be written to given file. Defaults to the
          standard output. File extension defines output
          format. Supported formats: html, csv, txt (default).

  -p, --plot=<file>[,options]
          plot statistics into a diagram. Image will be written to the
          given file. Requires Gnuplot. File extension defines image
          format. Supported formats: eps, gif, png, svg.
          Possible options are: "width=<int>" (default: 1024).

Examples:
  fmbt-stats -f times:median -p median.png test.log
  display median.png

  fmbt-stats -f times:total -o total.html -p total.svg test.log
  firefox total.html total.svg

  fmbt-stats -f speed:1,50 -o speed.csv -p speed.gif test.log

  fmbt-stats -f dist:next,sort -p dist.gif,width=2048 -o /dev/null test.log
"""

import commands
import sys
import operator
import subprocess
import getopt
import os
import re
import fmbt_config

MAXSPEED=100000

def error(msg):
    sys.stderr.write('fmbt-stats: ' + msg + '\n')
    sys.exit(1)

def read_from_log_duration_execaction(testlog_fileobj, include_regexps = []):
    cmd = ["fmbt-log","-f","$at $as|FMBT-STATS|$ax"]
    p = subprocess.Popen(cmd, shell=False, stdin=testlog_fileobj.fileno(), stdout=subprocess.PIPE)

    duration_actionname_list = []
    try:
        line = p.stdout.readline()
        while line:
            space = line.find(" ")
            actionname1, actionname2 = line[space+1:-1].split('|FMBT-STATS|')
            this_duration = float(line[:space])

            if actionname1 == actionname2:
                current_action = actionname1
            else:
                current_action = "%s => %s" % (actionname1, actionname2)

            skip_this_action = False
            if include_regexps:
                for ire in include_regexps:
                    if ire.match(actionname1) or ire.match(actionname2):
                        break # match!
                else:
                    # include regexps given but none of them match
                    skip_this_action = True
            if not skip_this_action:
                duration_actionname_list.append((this_duration, current_action))
            line = p.stdout.readline()
    except Exception, e:
        error('invalid line in fmbt-log output: "%s"' % line[:-1])

    if duration_actionname_list == []: error('no data')
    return duration_actionname_list

def read_from_log_timestamp_execaction(testlog_fileobj):
    cmd = ["fmbt-log","-f","$st $as|FMBT-STATS|$ax"]
    p = subprocess.Popen(cmd, shell=False, stdin=testlog_fileobj.fileno(), stdout=subprocess.PIPE)

    timestamp_actionname_list = []
    try:
        line = p.stdout.readline()
        while line:
            space = line.find(" ")
            actionname1, actionname2 = line[space+1:-1].split('|FMBT-STATS|')
            if actionname1 == actionname2:
                timestamp_actionname_list.append((float(line[:space]), actionname1))
            else:
                timestamp_actionname_list.append((float(line[:space]), "%s => %s" % (actionname1, actionname2)))

            line = p.stdout.readline()
    except Exception, e:
        error('invalid line in fmbt-log output: "%s"' % line[:-1])

    if timestamp_actionname_list == []: error('no output from fmbt-log')
    return timestamp_actionname_list

def read_from_log_possible_executed(testlog_fileobj):
    cmd = ["fmbt-log", "-f", "p:$am\\nx:$ax"]
    p = subprocess.Popen(cmd, shell=False, stdin=testlog_fileobj.fileno(), stdout=subprocess.PIPE)

    possible_actions = []
    executed_actions = []
    try:
        line = p.stdout.readline()
        while line:
            if line[0]=='x' and len(line) > 3:
                executed_actions.append(line[2:-1])
            elif line[0]=='p' and len(line) > 3:
                possible_actions.append(line[2:-1])
            line = p.stdout.readline()
    except Exception, e:
        error('invalid line in fmbt-log output: "%s"' % line[:-1])
    if possible_actions == []: error('no output from fmbt-log')
    return possible_actions, executed_actions

def read_from_log_possible_executed_tags(testlog_fileobj, to_or_from):
    if to_or_from.lower() == "from":
        tag_format = "$tb"
    else:
        tag_format = "$tg"
    cmd = ["fmbt-log", "-s", "|FMBT-STATS|", "-f", "p:$am\\nx:$ax\\nt:" + tag_format]
    p = subprocess.Popen(cmd, shell=False, stdin=testlog_fileobj.fileno(), stdout=subprocess.PIPE)

    possible_actions = []
    executed_actions = []
    tags = []
    try:
        line = p.stdout.readline()
        while line:
            if line[0]=='x' and len(line) > 3:
                executed_actions.append(line[2:-1])
            elif line[0]=='p' and len(line) > 3:
                possible_actions.append(line[2:-1])
            elif line[0]=='t' and len(line) > 3:
                tags.append(line[2:-1].split('|FMBT-STATS|'))
            line = p.stdout.readline()
    except Exception, e:
        error('invalid line in fmbt-log output: "%s"' % line[:-1])
    if possible_actions == []: error('no output from fmbt-log')
    return possible_actions, executed_actions, tags

def read_from_log_coverage_timestamp(testlog_fileobj):
    cmd = ["fmbt-log","-f","$sb $st"]
    p = subprocess.Popen(cmd, shell=False, stdin=testlog_fileobj.fileno(), stdout=subprocess.PIPE)

    coverage_timestamp = []
    try:
        line = p.stdout.readline()
        while line:
            splitted = line[:-1].split(' ', 1)
            if len(splitted) == 2 and splitted[0] and splitted[1]:
                coverage_timestamp.append(
                    (float(splitted[0]), float(splitted[1])))
            line = p.stdout.readline()
    except Exception, e:
        error('invalid line in fmbt-log output: "%s"' % line[:-1])
    if coverage_timestamp == []: error('no output from fmbt-log')
    return coverage_timestamp

def check_output_format(output_fileobj):
    """return csv, html or plot"""
    if '.' in output_fileobj.name: output_file_ext = output_fileobj.name.split('.')[-1].lower()
    else: output_file_ext = ""

    if output_file_ext in ['html', 'csv']: output_file_format = output_file_ext
    else: output_file_format = 'plot'
    return output_file_format

def write_output_file(output_fileobj, data_formatter, data):
    output_file_format = check_output_format(output_fileobj)

    output_table = data_formatter(output_file_format, data)
    output_fileobj.write("".join(output_table))

def init_plotting(plot_filename, plot_data_table):
    """returns gnuplot term and output definitions, and plot data filename"""
    if "," in plot_filename:
        plot_filename, plot_args = plot_filename.split(',',1)
        plot_args = plot_args.split(',')
    else: plot_args = []
    plot_opt_width=1024
    for a in plot_args:
        if a.startswith('width='): plot_opt_width = int(a.split('=')[1])

    plot_output_format = plot_filename.split('.')[-1] if '.' in plot_filename else plot_filename
    if plot_output_format in ['gif', 'png']:
        plot_output_format = 'set term ' + plot_output_format + (' size %d,768 10 xffffff' % (plot_opt_width,))
    elif plot_output_format in ['svg']:
        plot_output_format = 'set term ' + plot_output_format + (' size %d,768 fsize 10' % (plot_opt_width,))
    elif plot_output_format in ['ps', 'eps']:
        plot_output_format = 'set term postscript landscape "Helvetica" 10'
    elif plot_output_format in ['pdf']:
        plot_output_format = 'set term pdfcairo'
    output_filename = "/tmp/fmbt-stats.%s.dat" % (os.getpid(),)

    plot_output_format += '\nset output "%s"' % (plot_filename,)

    file(output_filename, "w").write("".join(plot_data_table))
    return plot_output_format, output_filename

def finish_plotting(plot_datafilename, gnuplot_commands):
    if not opt_debug:
        popen_args = {'stderr': subprocess.PIPE}
    else:
        popen_args = {}
    gnuplot_process = subprocess.Popen(["gnuplot"], shell=False,
                                       stdin=subprocess.PIPE,
                                       **popen_args)
    gnuplot_process.communicate(gnuplot_commands)
    os.remove(plot_datafilename)

def stats_cov(arg, testlog_fileobj, output_fileobj, plot_filename):
    arg_list = arg.split(",")
    xaxis = arg_list[0]
    if "all" in arg_list[1:]: print_every_step = True
    else: print_every_step = False
    if xaxis not in ["time", "steps"]:
        error('syntax error in coverage arguments "%s", expected "time" or "steps"' % (arg,))

    def format_data(out_format, data_cov_xaxis):
        title = 'Coverage in function of %s' % (xaxis,)
        header_format, datarow_format, footer_format = {}, {}, {}
        header_format['plot'] = '# ' + title + ('\n# %15s %11s\n' %
                                                (xaxis, "coverage"))
        if xaxis == "steps": datarow_format['plot'] = '%17s %11.8f\n'
        else: datarow_format['plot'] = '%17.6f %11.8f\n'
        footer_format['plot'] = ''

        header_format['csv'] = '"%s"\n"%s";"coverage"\n' % (title, xaxis)
        if xaxis == "steps": datarow_format['csv'] = '%s;%s\n'
        else: datarow_format['csv'] = '%.6f;%s\n'
        footer_format['csv'] = ''

        header_format['html'] = '<html><body>\n<h2>%s</h2>\n<table>\n<tr><th>%s</th><th>coverage</th></tr>\n' % (title, xaxis)
        if xaxis == "steps": datarow_format['html'] = '<tr><td>%s</td><td>%s</td></tr>\n'
        else: datarow_format['html'] = '<tr><td>%.6f</td><td>%s</td></tr>\n'
        footer_format['html'] = '</table></body></html>\n'

        output_table = [header_format[out_format]]
        for datarow in data_cov_xaxis:
            output_table.append(datarow_format[out_format] %
                                (datarow[1], datarow[0]))
        output_table.append(footer_format[out_format])
        return output_table

    coverage_timestamp = read_from_log_coverage_timestamp(testlog_fileobj)
    data_cov_xaxis = []
    if xaxis == "steps":
        last_coverage = -1
        i = 0
        for i, ct in enumerate(coverage_timestamp):
            if print_every_step or ct[0] != last_coverage:
                data_cov_xaxis.append((ct[0], i))
                last_coverage = ct[0]
    else:
        last_coverage = -1
        start_time = coverage_timestamp[0][1]
        prev_appended = False
        t = 1
        for c, t in coverage_timestamp:
            if print_every_step or c != last_coverage:
                data_cov_xaxis.append((c, t - start_time))
                last_coverage = c
                prev_appended = True
            else:
                prev_appended = False
        if not prev_appended:
            data_cov_xaxis.append((last_coverage, t - start_time))

    write_output_file(output_fileobj, format_data, data_cov_xaxis)

    if plot_filename:
        plot_term, plot_datafilename = init_plotting(plot_filename,
                                                     format_data('plot', data_cov_xaxis))
        if xaxis == "time": xaxis_label = "Time [s]"
        else: xaxis_label = "Steps"
        gnuplot_commands = """
set ylabel "Coverage"
set xlabel "%(xaxis)s"
unset key
%(plot_term)s
set grid ytics noxtics
plot [0:%(last_value)s] '%(plot_datafilename)s' using 1:2 with lines
""" % { 'plot_term': plot_term,
        'plot_datafilename': plot_datafilename,
        'last_value': data_cov_xaxis[-1][1],
        'xaxis' : xaxis_label }

        finish_plotting(plot_datafilename, gnuplot_commands)

def stats_speed(arg, testlog_fileobj, output_fileobj, plot_filename, print_duration=False):

    include_regexps = []
    averages = []
    for a in arg.split(','):
        if a.lower().startswith('include='):
            r = re.compile(a.split('=',1)[1])
            try:
                include_regexps.append(r)
            except:
                error('syntax error in speed include regular expression "%s"'
                      % (r,))
        elif a:
            try:
                averages.append(int(a))
            except ValueError:
                error('syntax error in speed argument "%s"'
                      % (a,))
    if averages == []:
        averages = [1]

    if print_duration:
        title = 'Average test step duration [s]'
    else:
        title = 'Average execution speed [test steps / s]'

    def format_data(out_format, data_speed_columns):
        if len(data_speed_columns) == 0: return []
        column_count = len(data_speed_columns[0])
        header_format, datarow_format, footer_format = {}, {}, {}
        header_format['plot'] = '# ' + title + '\n#' + (' '.join(['%11s' for _ in xrange(column_count)])) + '\n'
        datarow_format['plot'] = ('%11.3f ' * column_count) + '\n'
        footer_format['plot'] = ''

        header_format['csv'] = '"' + title + '"\n' + ';'.join(['"%s"' for _ in xrange(column_count)]) + '\n'
        datarow_format['csv'] = ';'.join(['%.3f' for _ in xrange(column_count)]) + '\n'
        footer_format['csv'] = ''

        header_format['html'] = '<html><body>\n<h2>' + title + ('</h2>\n<table>\n<tr><th>%s</th>' % ('</th><th>'.join(["%s" for _ in xrange(column_count)]))) + "\n"
        datarow_format['html'] = '<tr><td>%s</td></tr>\n' % ('</td><td>'.join(["%.3f" for _ in xrange(column_count)]),)
        footer_format['html'] = '</table></body></html>\n'

        header_row = tuple(["%s step(s)" % (n,) for n in averages])

        output_table = [header_format[out_format] % header_row]
        for datarow in data_speed_columns:
            output_table.append(datarow_format[out_format] % tuple(datarow))
        output_table.append(footer_format[out_format])
        return output_table

    timestamp_action_list = read_from_log_duration_execaction(testlog_fileobj, include_regexps)

    data = []
    last_durations = [[] for _ in xrange(len(averages))]
    for i in xrange(len(timestamp_action_list)): # xrange(min(averages), len(timestamp_action_list)):
        this_duration = timestamp_action_list[i][0]
        data.append([])
        for avg_index, avg in enumerate(averages):
            if len(last_durations[avg_index]) >= avg:
                last_durations[avg_index].pop(0)
            last_durations[avg_index].append(this_duration)
            avg_duration = sum(last_durations[avg_index]) / len(last_durations[avg_index])
            if print_duration:
                data[-1].append(avg_duration)
            else:
                if avg_duration == 0: data[-1].append(MAXSPEED)
                else: data[-1].append( 1/avg_duration )

    write_output_file(output_fileobj, format_data, data)

    if plot_filename:
        plot_term, plot_datafilename = init_plotting(plot_filename,
                                                     format_data('plot', data))
        plot_columns = []
        for column in xrange(len(data[0])):
            plot_columns.append(
                "'%s' using :%s title \"%s step(s)\"  with lines" % (
                    plot_datafilename, column + 1, averages[column]))
        gnuplot_commands = """
set ylabel "%(title)s"
set xlabel "Test step"
set log y
%(plot_term)s
set grid ytics noxtics
plot %(plot_columns)s
""" % { 'title': title,
        'plot_term': plot_term,
        'plot_filename': plot_filename,
        'plot_columns' : ','.join(plot_columns) }

        finish_plotting(plot_datafilename, gnuplot_commands)


def stats_times(arg, testlog_fileobj, output_fileobj, plot_filename):

    def format_data(out_format, min_med_max_tot_count_aname):
        title = 'Test step execution times'
        header_format, datarow_format, footer_format = {}, {}, {}
        header_format['plot'] = '# ' + title + '\n#%8s %9s %9s %9s %9s "%s"\n'
        datarow_format['plot'] = '%9.3f %9.3f %9.3f %9.0f %9s "%s"\n'
        footer_format['plot'] = ''

        header_format['csv'] = '"' + title + '"\n' + '%s;%s;%s;%s;%s;%s\n'
        datarow_format['csv'] = '%.3f;%.3f;%.3f;%.0f;%s;"%s"\n'
        footer_format['csv'] = ''

        header_format['html'] = '<html><body>\n<h2>' + title + '</h2><table>\n<tr><th>%s</th><th>%s</th><th>%s</th><th>%s</th><th>%s</th><th>%s</th></tr>\n'
        datarow_format['html'] = '<tr><td>%.3f</td><td>%.3f</td><td>%.3f</td><td>%.0f</td><td>%s</td><td>%s</td></tr>\n'
        footer_format['html'] = '</table></body></html>\n'

        header_row = ('min[ms]', 'med[ms]', 'max[ms]', 'total[ms]', 'count', 'action')

        output_table = [header_format[out_format] % header_row]
        for datarow in min_med_max_tot_count_aname:
            output_table.append(datarow_format[out_format] % datarow)
        output_table.append(footer_format[out_format])
        return output_table

    possible_args = ['min', 'median', 'max', 'total', 'count', 'name']
    if not arg in possible_args:
        error("unknown timer argument: '%s'. Use one of '%s'." %
              (arg, "', '".join(possible_args)))
    sort_by_field = possible_args.index(arg)

    action_exectimes = {} # map action name to list of exec time durations
    prev_timestamp = None
    for timestamp, actionname in read_from_log_timestamp_execaction(testlog_fileobj):
        if prev_timestamp != None:
            timedelta = timestamp - prev_timestamp
            if not prev_actionname in action_exectimes:
                action_exectimes[prev_actionname] = []
            action_exectimes[prev_actionname].append(timedelta)
        prev_timestamp = timestamp
        prev_actionname = actionname

    for a in action_exectimes:
        action_exectimes[a].sort()
    min_med_max_tot_count_aname = []
    for a in action_exectimes:
        exectimes = action_exectimes[a]
        min_med_max_tot_count_aname.append(
            (exectimes[0]*1000,
             exectimes[len(exectimes)/2]*1000,
             exectimes[-1]*1000,
             sum(exectimes)*1000,
             len(exectimes),
             a))
    min_med_max_tot_count_aname.sort(key=operator.itemgetter(sort_by_field, 4))

    write_output_file(output_fileobj, format_data, min_med_max_tot_count_aname)

    if plot_filename:

        plot_term, plot_datafilename = init_plotting(plot_filename,
                                                   format_data('plot', min_med_max_tot_count_aname))

        gnuplot_commands = """
set ylabel  "Execution times [ms]: min-median-max (red), total (blue)"
set y2label "Number of iterations (grey bar)"
unset key
set xtics rotate by -15
set log y
set log y2
set pointsize 1
set grid ytics mytics noxtics
%(plot_term)s
set boxwidth 0.2
plot [-1:] '%(plot_datafilename)s' using :5 with boxes fill solid 0.5 linecolor rgb "light-grey", '%(plot_datafilename)s' using :2:1:3:xtic(6) with errorbar pointtype 2 linecolor rgb "red", '%(plot_datafilename)s' using :4 with points pointtype 6 linecolor rgb "blue"
""" % {'plot_filename': plot_filename,
       'plot_datafilename': plot_datafilename,
       'plot_term': plot_term}

        finish_plotting(plot_datafilename, gnuplot_commands)


def stats_dist(arg, testlog_fileobj, output_fileobj, plot_filename):
    possible_actions, executed_actions = read_from_log_possible_executed(testlog_fileobj)

    def format_data(out_format, data_dict):
        # Uses title from stats_dist
        if not opt_sort: # sort actions in alphabetical order
            action_columns = sorted(data_dict.keys())
        else: # sort actions by counted steps
            action_sum_name = [ (sum(data_dict[a].values()), a) for a in data_dict.keys() ]
            action_sum_name.sort()
            action_columns = [a for (s, a) in action_sum_name]

        column_count = len(action_columns)
        header_format, datarow_format, footer_format = {}, {}, {}
        header_format['plot'] = '# ' + title + '\n' + (' '.join(['"%s"' for _ in xrange(column_count)])) + '\n'
        datarow_format['plot'] = ('%6d ' * column_count) + '"%s"\n'
        footer_format['plot'] = ''

        header_format['csv'] = '"' + title + '"\n' + (';'.join(['"%s"' for _ in xrange(column_count)])) + '\n'
        datarow_format['csv'] = ('%d;' * column_count) + '"%s"\n'
        footer_format['csv'] = ''

        header_format['html'] = '<html><body>\n<h2>' + title + '</h2>\n<table>\n<tr><th>' + '</th><th>'.join(['%s' for _ in xrange(column_count)]) + '</th></tr>\n'
        datarow_format['html'] = '<tr>' + ('<td>%d</td>' * column_count) + '<td>%s</td></tr>\n'
        footer_format['html'] = '</table></body></html>\n'

        output_table = [header_format[out_format] % tuple(action_columns)]
        for a in action_columns:
            datarow = []
            for a_distrib in action_columns:
                datarow.append(data_dict[a].get(a_distrib, 0))
            datarow.append(a)
            output_table.append(datarow_format[out_format] % tuple(datarow))
        return output_table

    arg_list = arg.split(",")
    opt_uniq = (arg_list.count('uniq') > 0)
    opt_sort = (arg_list.count('sort') > 0)
    opt_next = (arg_list[0] == 'next')
    opt_prev = (arg_list[0] == 'prev')
    opt_simple = (arg_list[0] == 'simple')

    if opt_simple:
        title = "Number of steps"
    elif not opt_uniq:
        if opt_next and not opt_uniq: title = "Number of next steps"
        elif opt_prev and not opt_uniq: title = "Number of previous steps"
    else:
        if opt_next: title = "Number of unique next steps"
        elif opt_prev: title = "Number of unique previous steps"

    # Create data dictionary:
    # { possible action_1 -> { next_action_1: count_1,
    #                          next_action_2: count_2,
    #                          ... }
    #   ...
    # }
    data = {}
    for a in possible_actions:
        data[a] = {}
    if executed_actions:
        prev = executed_actions[0]
        if opt_next:
            for next in executed_actions[1:]:
                if opt_uniq: data[prev][next] = 1
                else: data[prev][next] = data[prev].get(next, 0) + 1
                prev = next
        elif opt_prev:
            for next in executed_actions[1:]:
                if opt_uniq: data[next][prev] = 1
                else: data[next][prev] = data[next].get(prev, 0) + 1
                prev = next
        elif opt_simple:
            for act in executed_actions:
                data[act][act] = data[act].get(act, 0) + 1
        else:
            error('unknown dist argument "%s".' % (arg,))

    write_output_file(output_fileobj, format_data, data)

    if plot_filename:
        plot_term, plot_datafilename = init_plotting(plot_filename,
                                                     format_data('plot', data))
        if opt_simple: keyspec = "set nokey"
        else: keyspec = "set key outside right top vertical Left reverse noenhanced autotitles columnhead nobox"
        gnuplot_commands = """
%(plot_term)s

set ylabel "%(ylabel)s"

set grid ytics

set boxwidth .8
set style fill solid 1.00 border lt -1
set key samplen 4 spacing 1 width 0 height 0
%(keyspec)s
set style histogram rowstacked title offset character 0, 0, 0

set xtics border in scale 0,0 nomirror rotate by -15  offset character 0, 0, 0
set xtics  norangelimit font ",8"
set style data histograms
plot '%(plot_datafilename)s' using 1:xtic(%(actioncol)s), for[i=2:%(lastdatacol)s] '' using i
""" % {'plot_filename': plot_filename,
       'plot_datafilename': plot_datafilename,
       'plot_term': plot_term,
       'lastdatacol': len(data.keys()),
       'actioncol': len(data.keys())+1,
       'ylabel': title,
       'keyspec': keyspec
       }

        finish_plotting(plot_datafilename, gnuplot_commands)


def stats_tagdist(arg, testlog_fileobj, output_fileobj, plot_filename):
    possible_actions, executed_actions, tags = None, None, None

    def format_data(out_format, data_dict):
        # Uses title from stats_dist
        action_rows = sorted(data_dict.keys())
        all_tags = set()
        for act in action_rows:
            all_tags.update(data_dict[act].keys())
        tag_columns = sorted(all_tags)

        column_count = len(tag_columns)
        header_format, datarow_format, footer_format = {}, {}, {}
        header_format['plot'] = '# ' + title + '\n' + (' '.join(['"%s"' for _ in xrange(column_count)])) + '\n'
        datarow_format['plot'] = ('%6d ' * column_count) + '"%s"\n'
        footer_format['plot'] = ''

        header_format['csv'] = '"' + title + '"\n' + (';'.join(['"%s"' for _ in xrange(column_count)])) + '\n'
        datarow_format['csv'] = ('%d;' * column_count) + '"%s"\n'
        footer_format['csv'] = ''

        header_format['html'] = '<html><body>\n<h2>' + title + '</h2>\n<table>\n<tr><th>' + '</th><th>'.join(['%s' for _ in xrange(column_count)]) + '</th></tr>\n'
        datarow_format['html'] = '<tr>' + ('<td>%d</td>' * column_count) + '<td>%s</td></tr>\n'
        footer_format['html'] = '</table></body></html>\n'

        output_table = [header_format[out_format] % tuple(tag_columns)]
        for act in action_rows:
            datarow = []
            for tag in tag_columns:
                datarow.append(data_dict[act].get(tag, 0))
            datarow.append(act)
            output_table.append(datarow_format[out_format] % tuple(datarow))
        return output_table

    arg_list = arg.split(",")
    if arg_list[0] not in ['from', 'to']:
        error('illegal first argument: "%s"' % (arg_list[0],))
    opt_next = (arg_list[0] == 'from')
    opt_prev = (arg_list[0] == 'to')
    if not (opt_next or opt_prev): opt_next = True
    possible_actions, executed_actions, tags = read_from_log_possible_executed_tags(
        testlog_fileobj, "from" if opt_next else "to")
    if len(arg_list)>1:
        if arg_list[1].startswith('tags='):
            regex = arg_list[1].split('=',1)[1]
            try: opt_regex = re.compile(regex)
            except: error('illegal regular expression "%s".' % (regex,))
        else:
            error('illegal argument "%s".' % (arg_list[1],))
    else:
        opt_regex = re.compile('.*')

    if opt_next: title = "Number of steps from tags"
    elif opt_prev: title = "Number of steps to tags"

    # Create data dictionary:
    # { action_1 -> { tag_1: count_1,
    #                 tag_2: count_2,
    #           ... }
    #   ...
    # }
    all_tags = set()
    for state_tags in tags:
        all_tags.update(state_tags)
    all_tags = set([t for t in all_tags if opt_regex.match(t)])
    if len(all_tags) == 0:
        error('No tags.')

    data = {}
    for act in set(executed_actions):
        data[act] = {}
    if executed_actions:
        if opt_next or opt_prev:
            for index, state_tags in enumerate(tags):
                for tag in state_tags:
                    if not tag in all_tags: continue
                    if index > len(executed_actions) - 1: break
                    next_action = executed_actions[index]
                    data[next_action][tag] = data[next_action].get(tag, 0) + 1
        else:
            error('unknown dist argument "%s".' % (arg,))

    write_output_file(output_fileobj, format_data, data)

    if plot_filename:
        plot_term, plot_datafilename = init_plotting(plot_filename,
                                                     format_data('plot', data))
        tag_columns = sorted(all_tags)

        keyspec = "set key outside right top vertical Left reverse noenhanced autotitles columnhead nobox"
        gnuplot_commands = """
%(plot_term)s

set ylabel "%(ylabel)s"

set grid ytics

set boxwidth .8
set style fill solid 1.00 border lt -1
set key samplen 4 spacing 1 width 0 height 0
%(keyspec)s
set style histogram rowstacked title offset character 0, 0, 0

set xtics border in scale 0,0 nomirror rotate by -15  offset character 0, 0, 0
set xtics  norangelimit font ",8"
set style data histograms
plot '%(plot_datafilename)s' using 1:xtic(%(actioncol)s), for[i=2:%(lastdatacol)s] '' using i
""" % {'plot_filename': plot_filename,
       'plot_datafilename': plot_datafilename,
       'plot_term': plot_term,
       'lastdatacol': len(tag_columns),
       'actioncol': len(tag_columns)+1,
       'ylabel': title,
       'keyspec': keyspec
       }

        finish_plotting(plot_datafilename, gnuplot_commands)


if __name__ == '__main__':
    testlog_fileobj = sys.stdin
    output_fileobj = sys.stdout
    output_fileobj_close = 0
    output_format = 'times:total'
    plot_filename = None
    opt_debug = False

    opts, remainder = getopt.getopt(
        sys.argv[1:], 'dhf:o:p:VE',
        ['debug', 'help', 'format=', 'output=', 'plot=', 'version'])
    for opt, arg in opts:
        if opt in ['-h', '--help']:
            print __doc__
            sys.exit(0)
        elif opt in ['-V', '--version']:
            print "Version " + fmbt_config.fmbt_version + fmbt_config.fmbt_build_info
            sys.exit(0)
        elif opt in ['-d', '--debug']:
            opt_debug = True
        elif opt in ['-f', '--format']:
            output_format = arg
        elif opt in ['-o', '--output'] and not arg in ['', '-']:
            output_fileobj = file(arg, 'w')
            output_fileobj_close = 1
        elif opt in ['-p', '--plot']:
            plot_filename = arg

    if remainder and remainder[0] != "-":
        testlog_fileobj = file(remainder[0], "r")

    if output_format.startswith('times'):
        if ':' in output_format:
            param = output_format.split(':',1)[1]
        else:
            param = 'total'
        t = stats_times(param, testlog_fileobj, output_fileobj, plot_filename)

    elif output_format.startswith('speed') or output_format.startswith("duration"):
        if ':' in output_format:
            param = output_format.split(':',1)[1]
        else:
            param = '1'
        print_duration = output_format.startswith("duration")
        t = stats_speed(param, testlog_fileobj, output_fileobj, plot_filename, print_duration)

    elif output_format.startswith('dist'):
        if ':' in output_format:
            param = output_format.split(':',1)[1]
        else:
            param = 'next'
        t = stats_dist(param, testlog_fileobj, output_fileobj, plot_filename)

    elif output_format.startswith('tagdist'):
        if ':' in output_format:
            param = output_format.split(':',1)[1]
        else:
            param = 'from'
        t = stats_tagdist(param, testlog_fileobj, output_fileobj, plot_filename)

    elif output_format.startswith('cov'):
        if ':' in output_format:
            param = output_format.split(':',1)[1]
        else:
            param = 'steps'
        t = stats_cov(param, testlog_fileobj, output_fileobj, plot_filename)

    else:
        error('unknown format: %s' % (output_format,))

    if output_fileobj_close:
        output_fileobj.close()
