#!/bin/bash

# fMBT, free Model Based Testing tool
# Copyright (c) 2011, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU Lesser General Public License,
# version 2.1, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.

if [ "x$1" == "x" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "Usage: $0 modelname.lsts [format]"
    echo "Default format is pdf. Other supported formats are:"
    dot -Thelp 2>&1 | sed 's/.*://'
    exit 1
fi

UTILPATH="$(dirname "$0")"
FORMAT=${2-pdf}
OUTPUTFILE="/tmp/$(basename "$1").$FORMAT"

( $UTILPATH/lsts2dot --loops-as-props "$1" - | tee "$OUTPUTFILE.gv" | dot -T$FORMAT -o"$OUTPUTFILE" ) && {

    echo "Graphviz source saved to $OUTPUTFILE.gv"
    echo "Graphviz output saved to $OUTPUTFILE"
    echo "Displaying..."
    display "$OUTPUTFILE"

}
