#!/bin/bash

# fMBT, free Model Based Testing tool
# Copyright (c) 2011, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU Lesser General Public License,
# version 2.1, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.

# This script takes a list of model components as parameters. It
# generates non-flat model which is parallel composition of the
# components. Synchronisation of components is based on alphabets. The
# model is printed to the standard output.

REXTRULES="$(dirname "$0")"/rextendedrules.py

REXT_FILE=/tmp/parallel.rextrules

echo '' > $REXT_FILE

i=1
for lsts in "$@"; do
    echo "$i=\"$lsts\"" >> $REXT_FILE
    i=$(( $i + 1 ))
done

echo '(${.*}, "${(?!tau).*}") ALL(${.*},"$=2.") -> "$=2."' >> $REXT_FILE

$REXTRULES $REXT_FILE -
# rm -f $REXT_FILE
