.TH PYTHONSHARE-CLIENT 1 "Mar 2014" Linux "User Manuals"
.SH NAME
pythonshare\-client \- Code mobility client for Python
.SH SYNOPSIS
.SY pythonshare\-client
.OP \-\-password PASSWORD
.OP \-\-password\-file FILE
.OP \-C HOSTSPEC
.OP \-D
.OP \-o OUTFILE
.OP \-f FORMAT
.OP \-A
.OP \-S
.OP \-P
.OP \-c CODE
.OP \-e EXPR
.OP \-l LOGFILE
.OP \-p PORT
.OP \-\-password ALG:HASH
.OP \-\-password-file FILE
.OP \-\-interface interface
.OP \-n NS
.OP \-E HOSTSPEC
.OP \-I HOSTSPEC
.OP \-i CODE
.SY pythonshare\-client
.B \-h
|
.B \-\-help
.SH DESCRIPTION
\fBpythonshare\-client\fR offers commandline interface for executing
Python code and evaluating Python expressions in \fBpythonshare\-server\fRs.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
print help, then exit.
.SH AUTHOR
Written by Antti Kervinen.
.SH "REPORTING BUGS"
Report bugs to https://github.com/01org/fMBT/issues
.SH COPYRIGHT
Copyright \(co 2014 Intel Corporation.
.SH "SEE ALSO"
.BR pythonshare\-server (1)
